sudo: false
language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - yarn run prebuild && yarn run test:prod && yarn run build && yarn run copy-index
after_success:
  - yarn run semantic-release
