language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - yarn run test:prod && yarn run build && yarn run dist-to-bin && ls bin
after_success:
  # - yarn run report-coverage
  # - yarn run deploy-docs
  - ls
  - yarn run semantic-release
